version: "3.9"

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:15.2-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=boilerplate
      - POSTGRES_PASSWORD=boilerplate
      - POSTGRES_DB=boilerplate_dev

volumes:
  postgres_data:
